PUSHD tools\strawberry-perl-5.32.1.1-64bit-portable

SET PATH=%CD%\perl\site\bin;%CD%\perl\bin;%CD%\c\bin;%PATH%

SET TERM=
SET PERL_JSON_BACKEND=
SET PERL_YAML_BACKEND=
SET PERL5LIB=
SET PERL5OPT=
SET PERL_MM_OPT=
SET PERL_MB_OPT=

POPD
