#!/usr/bin/env python3

import os
import sys
import re

import getopt

import glob

STATE_INIT = 0
STATE_BLOCK = 1

def usage():
    print("Usage : {0} -o <output> <input>...".format(sys.argv[0]))

def get_apis(filepath):
    items = []

    fp_in = open(filepath, mode="r", encoding="utf-8")

    while 1 :
        line = fp_in.readline()
        if not line :
            break

        line = re.sub(r'\r?\n?$', '', line)
        m = re.search(r'^def ([A-Za-z0-9_]+)', line)
        if m :
            func = m.group(1)
            items.append(func)

    fp_in.close()

    return items

def main():
    ret = 0

    try:
        options, args = getopt.getopt(
            sys.argv[1:],
            "hvo:p:n:",
            [
                "help",
                "version",
                "output=",
                "project=",
                "name=",
            ],
        )
    except getopt.GetoptError as err:
        print(str(err))
        sys.exit(1)

    output = None
    project = None
    name = None

    for option, optarg in options:
        if option == "-v":
            usage()
            sys.exit(1)
        elif option in ("-h", "--help"):
            usage()
            sys.exit(1)
        elif option in ("-o", "--output"):
            output = optarg
        elif option in ("-p", "--project"):
            project = optarg
        elif option in ("-n", "--name"):
            name = optarg
        else:
            assert False, "unknown option"

    #if project is None:
    #    print('ERROR: no project option', file=sys.stderr)
    #    ret += 1

    #if name is None:
    #    print('ERROR: no name option', file=sys.stderr)
    #    ret += 1

    if output is not None :
        fp = open(output, mode="w", encoding="utf-8")
    else :
        fp = sys.stdout

    if ret != 0:
        sys.exit(ret)

    api_list = {}

    for target_dir in args:
        target_dir = re.sub(r'/$', '', target_dir)

        items = glob.glob(target_dir + '/**/*_api.py', recursive=True)

        for filepath in items:
            print('DEBUG: {0}'.format(filepath), file=sys.stderr)
            apis = get_apis(filepath)

            filename = os.path.basename(filepath)
            module = re.sub(r'_api.py$', '', filename)

            api_list[module] = apis


    fp.write('# generated by {0}\n'.format(sys.argv[0]))
    fp.write('from django.urls import path\n')
    for module in api_list:
        for api in api_list[module]:
            fp.write('from myapp.views.{0}_api import {1}\n'.format(module, api))

    fp.write('\n')
    fp.write('urlpatterns = [\n')
    for module in api_list:
        for api in api_list[module]:
            m = re.search(r'\w+_(.\w+)_api$', api)
            if m :
                action = m.group(1)
            else :
                print('ERROR: invalid api name, {0}'.format(api))
                sys.exit(1)

            if action in ('detail', 'delete'):
                action = '<int:{0}_id>'.format(module)

            fp.write("    path('api/{0}/{1}/', {2}),\n".format(module, action, api))

    fp.write(']\n')

    if output is not None:
        fp.close()

if __name__ == "__main__":
    main()

