#!/usr/bin/env python3

import os
import sys
import re

import getopt

import glob

STATE_INIT = 0
STATE_BLOCK = 1

def usage():
    print("Usage : {0} -o <output> <input>...".format(sys.argv[0]))

def get_apis(filepath):
    items = []

    fp_in = open(filepath, mode="r", encoding="utf-8")

    while 1 :
        line = fp_in.readline()
        if not line :
            break

        line = re.sub(r'\r?\n?$', '', line)
        m = re.search(r'^def ([A-Za-z0-9_]+)', line)
        if m :
            func = m.group(1)
            items.append(func)

    fp_in.close()

    return items

def get_class_or_def(filepath):
    items = []

    fp_in = open(filepath, mode="r", encoding="utf-8")

    while 1 :
        line = fp_in.readline()
        if not line :
            break

        line = re.sub(r'\r?\n?$', '', line)
        m = re.search(r'^(class|def) ([A-Za-z0-9_]+)', line)
        if m :
            item = m.group(2)
            items.append(item)

    fp_in.close()

    return items


def main():
    ret = 0

    try:
        options, args = getopt.getopt(
            sys.argv[1:],
            "hvo:p:n:",
            [
                "help",
                "version",
                "output=",
                "project=",
                "name=",
            ],
        )
    except getopt.GetoptError as err:
        print(str(err))
        sys.exit(1)

    output = None
    project = None
    name = None

    for option, optarg in options:
        if option == "-v":
            usage()
            sys.exit(1)
        elif option in ("-h", "--help"):
            usage()
            sys.exit(1)
        elif option in ("-o", "--output"):
            output = optarg
        elif option in ("-p", "--project"):
            project = optarg
        elif option in ("-n", "--name"):
            name = optarg
        else:
            assert False, "unknown option"

    #if project is None:
    #    print('ERROR: no project option', file=sys.stderr)
    #    ret += 1

    #if name is None:
    #    print('ERROR: no name option', file=sys.stderr)
    #    ret += 1

    if output is not None :
        fp = open(output, mode="w", encoding="utf-8")
    else :
        fp = sys.stdout

    if ret != 0:
        sys.exit(ret)

    api_list = {}

    items = {}

    for target_dir in args:
        target_dir = re.sub(r'/$', '', target_dir)

        filepaths = glob.glob(target_dir + '/**/*.py', recursive=True)

        for filepath in filepaths:
            filename = os.path.basename(filepath)
            if filename == '__init__.py' :
                continue

            module   = re.sub(r'\.py$', '', filename)
            print('DEBUG: {0}'.format(filepath), file=sys.stderr)
            print('DEBUG: {0}'.format(filename), file=sys.stderr)
            print('DEBUG: {0}'.format(module), file=sys.stderr)

            items[module] = get_class_or_def(filepath)

    fp.write('# generated by {0}\n'.format(sys.argv[0]))
                
    for module in items:
        for name in items[module]:
            fp.write('from .{0} import {1}\n'.format(module, name))

    if output is not None:
        fp.close()

if __name__ == "__main__":
    main()

