#!/usr/bin/env python3
# file: src/amcli/commands/generate_testscript/add.py

import os
import json

FIXED_UUID = "7c9f2b84-2e61-4c3b-9a7d-5f1c3e2d48b0"
DEBUG = os.environ.get("VERBOSE", "0") != "0"

HEADER = f"""#!/bin/sh

# Generated by generate_testscript/add.py
# UUID: {FIXED_UUID}

. ./.env

if [ -z "$BASE_URL" ]; then
    echo "ERROR: BASE_URL is not set in .env"
    exit 1
fi

echo "Using BASE_URL=$BASE_URL"
echo
"""

def tap_header(total_tests):
    return f"echo \"1..{total_tests}\"\n\n"


TEMPLATE_MODEL_FILE = """
echo "=== Registering {model} from {jsonfile} ==="

res=$(curl -s -k \
  -X POST "${{BASE_URL}}/api/{model_plural}/" \
  -H "Content-Type: application/json" \
  -d @"{jsonfile}")

echo "[DEBUG] POST response:"
echo "$res"

id=$(echo "$res" | jq -r '.{pk_field}')

if [ "$id" = "null" ] || [ -z "$id" ]; then
    echo "not ok - add {model} failed ({pk_field} not found)"
else
    echo "ok - add {model} succeeded"
    echo "$id" > ".id_{model}"
fi

echo
"""


def normalize_value(k, v):
    if k == "ipv4s" and isinstance(v, dict):
        return "[]"
    return json.dumps(v)


TEMPLATE_MODEL_FK = """
echo "=== Registering {model} (FK injected) ==="

json_fk=$(cat <<EOF
{{
  "{pk_field}": "{pk_value}",
  {extra_fields}
  "device_id": $(cat .id_device)
}}
EOF
)

res=$(curl -s -k \
  -X POST "${{BASE_URL}}/api/{model_plural}/" \
  -H "Content-Type: application/json" \
  -d "$json_fk")

echo "[DEBUG] POST response:"
echo "$res"

id=$(echo "$res" | jq -r '.{pk_field}')

if [ "$id" = "null" ] || [ -z "$id" ]; then
    echo "not ok - add {model} failed ({pk_field} not found)"
else
    echo "ok - add {model} succeeded"
    echo "$id" > ".id_{model}"
fi

echo
"""


TEMPLATE_DM = """
echo "=== Registering DeviceManager (device_id={device}, manager_id={manager}) ==="

json_dm=$(cat <<EOF
{{
  "device_id": "{device}",
  "manager_id": "{manager}"
}}
EOF
)

res=$(curl -s -k \
  -X POST "${{BASE_URL}}/api/devicemanager/" \
  -H "Content-Type: application/json" \
  -d "$json_dm")

echo "[DEBUG] POST response:"
echo "$res"

id=$(echo "$res" | jq -r '.id')

if [ "$id" = "null" ] || [ -z "$id" ]; then
    echo "not ok - add devicemanager failed"
else
    echo "ok - add devicemanager succeeded"
fi

echo
"""


def run_add(outpath, json_files, schema):

    script = HEADER

    total_tests = len(json_files)

    has_device = any("device" in jf for jf in json_files)
    has_manager = any("manager" in jf for jf in json_files)

    if has_device and has_manager:
        total_tests += 1

    script += tap_header(total_tests)

    # models + through_models を model_map に登録
    model_map = { key.lower(): key for key in schema["models"].keys() }
    for tm in schema.get("through_models", []):
        name = tm["name"]
        model_map[name.lower()] = name

    device_id_var = None
    manager_id_var = None

    for jf in json_files:
        base = os.path.basename(jf)
        model = base.split("_", 1)[1].replace(".json", "")

        model_cap = model_map[model]

        # through_models の PK は常に "id"
        if model_cap in [tm["name"] for tm in schema.get("through_models", [])]:
            pk_field = "id"
        else:
            pk_field = schema["primary_keys"][model_cap]

        model_plural = model + "s"

        with open(jf, "r", encoding="utf-8") as fp:
            data = json.load(fp)

        # through_models の JSON には id が無いので pk_value は空
        if model_cap in [tm["name"] for tm in schema.get("through_models", [])]:
            pk_value = ""
        else:
            pk_value = data[pk_field]

        if model in ("comment", "netif", "os", "remark"):

            extra_fields = ",\n  ".join(
                f"\"{k}\": {normalize_value(k, v)}"
                for k, v in data.items()
                if k not in (pk_field, "device_id")
            )

            if extra_fields:
                extra_fields = extra_fields + ","

            script += TEMPLATE_MODEL_FK.format(
                model=model,
                model_plural=model_plural,
                pk_field=pk_field,
                pk_value=pk_value,
                extra_fields=extra_fields,
            )

        else:
            script += TEMPLATE_MODEL_FILE.format(
                model=model,
                model_plural=model_plural,
                jsonfile=base,
                pk_field=pk_field
            )

        if model == "device":
            device_id_var = ".id_device"
        if model == "manager":
            manager_id_var = ".id_manager"

    if device_id_var and manager_id_var:
        script += TEMPLATE_DM.format(
            device=f"$(cat {device_id_var})",
            manager=f"$(cat {manager_id_var})"
        )

    script += "\n# End of file (generate_testscript/add.py)\n"

    with open(outpath, "w", encoding="utf-8") as f:
        f.write(script)

    os.chmod(outpath, 0o755)

    print(f"Generated add script: {outpath}")
