#!/usr/bin/env python3
# file: src/amcli/commands/generate_testscript/add.py

import os
import json

FIXED_UUID = "7c9f2b84-2e61-4c3b-9a7d-5f1c3e2d48b0"
DEBUG = os.environ.get("VERBOSE", "0") != "0"

HEADER = f"""#!/bin/sh

# Generated by generate_testscript/add.py
# UUID: {FIXED_UUID}

. ./.env

if [ -z "$BASE_URL" ]; then
    echo "ERROR: BASE_URL is not set in .env"
    exit 1
fi

echo "Using BASE_URL=$BASE_URL"
echo
"""

def tap_header(total_tests):
    return f"echo \"1..{total_tests}\"\n\n"


TEMPLATE_MODEL_FILE = """
echo "=== Registering {model} from {jsonfile} ==="

res=$(curl -s -k \
  -X POST "${{BASE_URL}}/api/{model_plural}/" \
  -H "Content-Type: application/json" \
  -d @"{jsonfile}")

echo "[DEBUG] POST response:"
echo "$res"

id=$(echo "$res" | jq -r '.{pk_field}')

if [ "$id" = "null" ] || [ -z "$id" ]; then
    echo "not ok - add {model} failed ({pk_field} not found)"
else
    echo "ok - add {model} succeeded"
    echo "$id" > ".id_{model}"
fi

echo
"""


def normalize_value(k, v):
    if k == "ipv4s" and isinstance(v, dict):
        return "[]"
    return json.dumps(v)


TEMPLATE_MODEL_FK = """
echo "=== Registering {model} (FK injected) ==="

json_fk=$(cat <<EOF
{{
  {json_body}
}}
EOF
)

res=$(curl -s -k \
  -X POST "${{BASE_URL}}/api/{model_plural}/" \
  -H "Content-Type: application/json" \
  -d "$json_fk")

echo "[DEBUG] POST response:"
echo "$res"

id=$(echo "$res" | jq -r '.{pk_field}')

if [ "$id" = "null" ] || [ -z "$id" ]; then
    echo "not ok - add {model} failed ({pk_field} not found)"
else
    echo "ok - add {model} succeeded"
    echo "$id" > ".id_{model}"
fi

echo
"""


def run_add(outpath, json_files, schema):

    script = HEADER

    # through_models は API 非公開なので除外
    through_names = []

    # テスト数は純粋に JSON ファイル数のみ
    total_tests = len(json_files)
    script += tap_header(total_tests)

    # モデル名マップ（through_models は含めない）
    model_map = { key.lower(): key for key in schema["models"].keys() }

    for jf in json_files:
        base = os.path.basename(jf)
        model = base.split("_", 1)[1].replace(".json", "")

        model_cap = model_map[model]

        pk_field = schema["primary_keys"][model_cap]
        model_plural = model + "s"

        with open(jf, "r", encoding="utf-8") as fp:
            data = json.load(fp)

        # FK を持つモデル
        if model in ("comment", "netif", "os", "remark"):

            body_items = []
            for k, v in data.items():
                if k not in (pk_field, "device_id"):
                    body_items.append(f"\"{k}\": {normalize_value(k, v)}")

            body_items.append(f"\"device_id\": $(cat .id_device)")

            json_body = ",\n  ".join(body_items)

            script += TEMPLATE_MODEL_FK.format(
                model=model,
                model_plural=model_plural,
                pk_field=pk_field,
                json_body=json_body,
            )

        else:
            script += TEMPLATE_MODEL_FILE.format(
                model=model,
                model_plural=model_plural,
                jsonfile=base,
                pk_field=pk_field
            )

    script += "\n# End of file (generate_testscript/add.py)\n"

    with open(outpath, "w", encoding="utf-8") as f:
        f.write(script)

    os.chmod(outpath, 0o755)

    print(f"Generated add script: {outpath}")
