#!/usr/bin/env python3

import sys
import yaml
import getopt


def read_yaml(path):
    with open(path, "r", encoding="utf-8") as fp:
        return yaml.safe_load(fp)


def usage():
    print(f"Usage: {sys.argv[0]} -o <output> <ref_yaml>...")


def main():
    options, args = getopt.getopt(
        sys.argv[1:], "ho:", ["help", "output="]
    )

    output = None

    for opt, val in options:
        if opt in ("-h", "--help"):
            usage()
            return
        elif opt in ("-o", "--output"):
            output = val

    if not args:
        print("ERROR: No *_ref.yaml files provided")
        usage()
        return

    # ------------------------------------------------------------
    # 1. 全 *_ref.yaml を読み込む
    # ------------------------------------------------------------
    models = {}  # model → fields

    for filepath in args:
        data = read_yaml(filepath)
        model = data["name"]
        fields = data["fields"]
        models[model] = fields

    # ------------------------------------------------------------
    # 2. 依存関係とフィールド分類を抽出
    # ------------------------------------------------------------
    meta = {
        "models": {},
        "dependencies": {},
        "field_categories": {
            "CharField": [],
            "JSONField": [],
            "ForeignKey": [],
            "OneToOneField": [],
            "ManyToManyField": [],
            "Special": []
        }
    }

    for model, fields in models.items():
        meta["models"][model] = {"fields": fields}

        deps = []

        for fname, fdef in fields.items():
            ftype = fdef["type"]

            # 依存関係
            if ftype in ("ForeignKey", "OneToOneField", "ManyToManyField"):
                deps.append(fdef["to"])

            # フィールド分類
            if ftype in meta["field_categories"]:
                meta["field_categories"][ftype].append(f"{model}.{fname}")
            elif fname == "gateway":
                meta["field_categories"]["Special"].append(f"{model}.{fname}")

        meta["dependencies"][model] = deps

    # ------------------------------------------------------------
    # 3. YAML 出力
    # ------------------------------------------------------------
    out = open(output, "w", encoding="utf-8") if output else sys.stdout
    out.write(f"# Generated by generate_meta.py\n")
    out.write('---\n')
    yaml.dump(meta, out, allow_unicode=True, sort_keys=False)
    if output:
        out.close()


if __name__ == "__main__":
    main()

