---
assets_table:
- name: aid
  type: TEXT
- name: name
  type: TEXT
- name: descr
  type: TEXT

interfaces_table:
- name: aid
  type: TEXT
- name: ifid
  type: TEXT
- name: prop
  type: TEXT
- name: val
  type: TEXT

applications_table:
- name: aid
  type: TEXT
- name: appid
  type: TEXT
- name: prop
  type: TEXT
- name: val
  type: TEXT

