from pathlib import Path
from jinja2 import Environment, FileSystemLoader

from .reader import read_json
from .modelgen import generate_model_lines
from amcli.utils.constants import normalize_field_type


def run(loader_dir, output_file, input_files):
    env = Environment(
        loader=FileSystemLoader(loader_dir),
        autoescape=False
    )
    template = env.get_template("model_template.j2")

    output_path = Path(output_file).resolve()
    fp = open(output_path, mode="w", encoding="utf-8")

    fp.write("# Generated by amcli genmodel\n")
    fp.write("from django.db import models\n\n")

    for filepath in input_files:
        data = read_json(filepath)

        for fname, fdef in data["fields"].items():
            fdef["type"] = normalize_field_type(fdef["type"])

        model = data["name"]

        field_lines, str_method, meta_lines = generate_model_lines(data)

        content = template.render(
            model=model,
            field_lines=field_lines,
            str_method=str_method,
            meta_lines=meta_lines,
        )

        fp.write(content + "\n\n")

    fp.close()
    print(f"[amcli] Generated model: {output_path}")

