#!/usr/bin/env python3

import sys
import getopt
import yaml
from collections import defaultdict, deque


def usage():
    print(f"Usage : {sys.argv[0]} -o depend.yaml schema.yaml")


def read_yaml(path):
    with open(path, "r", encoding="utf-8") as fp:
        return yaml.safe_load(fp)


# ---------------------------------------------------------
# トポロジカルソート
# ---------------------------------------------------------
def topo_sort(dep_map):
    graph = defaultdict(list)
    indegree = defaultdict(int)

    # 初期化
    for model, parents in dep_map.items():
        indegree[model] = len(parents)
        for p in parents:
            graph[p].append(model)

    # 入次数0のノードから開始
    queue = deque([m for m, d in indegree.items() if d == 0])
    order = []

    while queue:
        m = queue.popleft()
        order.append(m)

        for child in graph[m]:
            indegree[child] -= 1
            if indegree[child] == 0:
                queue.append(child)

    return order


# ---------------------------------------------------------
# main
# ---------------------------------------------------------
def main():
    try:
        options, args = getopt.getopt(
            sys.argv[1:], "hvo:", ["help", "version", "output="]
        )
    except getopt.GetoptError as err:
        print(str(err))
        sys.exit(1)

    output = None

    for option, optarg in options:
        if option == "-v":
            usage()
            sys.exit(1)
        elif option in ("-h", "--help"):
            usage()
            sys.exit(1)
        elif option in ("-o", "--output"):
            output = optarg

    if not args:
        print("Error: schema.yaml must be specified")
        sys.exit(1)

    schema_path = args[0]
    schema = read_yaml(schema_path)

    # schema.yaml から dependencies を取得（順序保持）
    dep_map = schema.get("dependencies", {})

    # トポロジカルソートで loaddata 順を決定
    load_order = topo_sort(dep_map)

    # ★ Device を最優先にする（暫定対応）
    if "Device" in load_order:
        load_order = ["Device"] + [m for m in load_order if m != "Device"]

    # 逆向き依存を生成（参照先 → 参照元）
    reverse_map = {model: [] for model in dep_map}

    # ★ dep_map の順序をそのまま使う（元の動作を再現）
    for model, parents in dep_map.items():
        for p in parents:
            reverse_map[p].append(model)

    # depend.yaml の出力
    result = {
        "dependencies": dep_map,
        "reverse_dependencies": reverse_map,
        "load_order": load_order,
    }

    yaml_text = yaml.dump(result, sort_keys=False, allow_unicode=True)

    if output:
        with open(output, "w", encoding="utf-8") as fp:
            fp.write("# Generated by generate_depend.py\n")
            fp.write("---\n")
            fp.write(yaml_text)
    else:
        print("---")
        print(yaml_text)


if __name__ == "__main__":
    main()
