#!/usr/bin/env python3

import sys
import getopt
import yaml


def read_yaml(path):
    with open(path, "r", encoding="utf-8") as fp:
        return yaml.safe_load(fp)


def collect_models(ref_files):
    """*_ref.yaml から models セクションを構築"""
    models = {}

    for path in ref_files:
        data = read_yaml(path)
        name = data["name"]
        fields = data.get("fields", {})
        models[name] = {"fields": fields}

    return models


def collect_dependencies(models):
    """ForeignKey / OneToOne / ManyToMany から依存関係を抽出"""
    deps = {m: [] for m in models}

    for model, data in models.items():
        fields = data["fields"]
        for fname, fdef in fields.items():
            ftype = fdef.get("type")
            to = fdef.get("to")

            if ftype in ("ForeignKey", "OneToOneField", "ManyToManyField"):
                if to:
                    deps[model].append(to)

    return deps


def collect_field_categories(models):
    """フィールドタイプごとに分類"""
    categories = {}

    for model, data in models.items():
        fields = data["fields"]
        for fname, fdef in fields.items():
            ftype = fdef.get("type", "Unknown")
            categories.setdefault(ftype, []).append(f"{model}.{fname}")

    return categories


def main():
    try:
        opts, args = getopt.getopt(
            sys.argv[1:], "ho:", ["help", "output="]
        )
    except getopt.GetoptError as err:
        print(str(err))
        sys.exit(1)

    output = "schema.yaml"

    for opt, val in opts:
        if opt in ("-h", "--help"):
            print("Usage: generate_schema.py -o schema.yaml template/app/*_ref.yaml")
            return
        elif opt in ("-o", "--output"):
            output = val

    if not args:
        print("ERROR: *_ref.yaml files must be specified")
        return

    ref_files = args

    # --- 解析 ---
    models = collect_models(ref_files)
    dependencies = collect_dependencies(models)
    field_categories = collect_field_categories(models)

    # --- schema.yaml の構造 ---
    schema = {
        "models": models,
        "dependencies": dependencies,
        "field_categories": field_categories,
    }

    # --- 出力 ---
    with open(output, "w", encoding="utf-8") as fp:
        fp.write("# Generated by generate_schema.py\n")
        yaml.dump(schema, fp, allow_unicode=True, sort_keys=False)


if __name__ == "__main__":
    main()

