# amcli/commands/generate_model.py

from pathlib import Path
import json
from jinja2 import Environment, FileSystemLoader

from amcli.utils.constants import FieldType, normalize_field_type


def read_json(filepath):
    with open(filepath, mode="r", encoding="utf-8") as fp:
        return json.load(fp)


# ------------------------------------------------------------
# フィールド行の生成
# ------------------------------------------------------------
def render_default(k, v):
    if k == "default" and (v in ["list", "dict"]):
        return f"default={v}"
    elif k == "on_delete":
        return f"{k}=models.{v}"
    else:
        return f"{k}={repr(v)}"


def render_simple_field(fname, field_def):
    args = []
    for k, v in field_def.items():
        if k == "type":
            continue
        if k is None:
            k = "null"
        args.append(render_default(k, v))
    arg_str = ", ".join(args)
    return f"{fname} = models.{field_def['type'].value}({arg_str})"


def render_relation_field(fname, field_def, ftype: FieldType):
    args = []

    # to=
    args.append(f"to={repr(field_def['to'])}")

    # on_delete=
    val = field_def.get("on_delete", "CASCADE")
    if isinstance(val, str) and val.startswith("models."):
        args.append(f"on_delete={val}")
    else:
        args.append(f"on_delete=models.{val}")

    # その他
    for k, v in field_def.items():
        if k in ["type", "to", "on_delete"]:
            continue
        if k is None:
            k = "null"
        args.append(render_default(k, v))

    arg_str = ", ".join(args)
    return f"{fname} = models.{ftype.value}({arg_str})"


def render_many_to_many_field(fname, field_def, model_name):
    args = []

    # to='Device'
    args.append(repr(field_def["to"]))

    # その他
    for k, v in field_def.items():
        if k in ["type", "to"]:
            continue
        args.append(render_default(k, v))

    # related_name が無ければ自動付与
    if not any(a.startswith("related_name=") for a in args):
        args.append(f"related_name='{model_name.lower()}s'")

    arg_str = ", ".join(args)
    return f"{fname} = models.ManyToManyField({arg_str})"


# ------------------------------------------------------------
# __str__ の生成
# ------------------------------------------------------------
def generate_str_method(fields):
    id_field = None
    name_field = None
    address_field = None
    first_field = None

    for fname in fields:
        if first_field is None:
            first_field = fname
        if fname.endswith("_id"):
            id_field = fname
        if fname == "name":
            name_field = fname
        if fname == "address":
            address_field = fname

    if id_field:
        if name_field:
            return f'return f"{{self.{id_field}}}: {{self.{name_field}}}"'
        elif address_field:
            return f'return f"{{self.{id_field}}}: {{self.{address_field}}}"'
        else:
            return f'return f"{{self.{id_field}}}"'
    elif name_field:
        return f'return f"{{self.{name_field}}}"'
    elif address_field:
        return f'return f"{{self.{address_field}}}"'
    else:
        return f'return f"{{self.{first_field}}}"'


# ------------------------------------------------------------
# モデル 1 つ分の生成
# ------------------------------------------------------------
def generate_model_lines(data):
    name = data["name"]
    fields = data["fields"]

    field_lines = []

    for fname, field_def in fields.items():
        ftype = normalize_field_type(field_def["type"])

        # ForeignKey / OneToOne
        if ftype in (FieldType.FOREIGN_KEY, FieldType.ONE_TO_ONE):
            line = render_relation_field(fname, field_def, ftype)
            field_lines.append(line)

        elif ftype == FieldType.MANY_TO_MANY:
            line = render_many_to_many_field(fname, field_def, name)
            field_lines.append(line)

        else:
            line = render_simple_field(fname, field_def)
            field_lines.append(line)

    # __str__
    str_method = generate_str_method(list(fields.keys()))

    # Meta
    meta_lines = []
    if "meta" in data:
        for k, v in data["meta"].items():
            meta_lines.append(f"{k} = {repr(v)}")

    return field_lines, str_method, meta_lines


# ------------------------------------------------------------
# amcli 用 run()
# ------------------------------------------------------------
def run(loader_dir, output_file, input_files):
    # Jinja2
    env = Environment(
        loader=FileSystemLoader(loader_dir),
        autoescape=False
    )
    template = env.get_template("model_template.j2")

    # 出力
    output_path = Path(output_file).resolve()
    fp = open(output_path, mode="w", encoding="utf-8")

    fp.write("# Generated by amcli genmodel\n")
    fp.write("from django.db import models\n\n")

    # 各モデルを生成
    for filepath in input_files:
        data = read_json(filepath)

        # type を Enum に正規化
        for fname, fdef in data["fields"].items():
            fdef["type"] = normalize_field_type(fdef["type"])

        model = data["name"]

        field_lines, str_method, meta_lines = generate_model_lines(data)

        content = template.render(
            model=model,
            field_lines=field_lines,
            str_method=str_method,
            meta_lines=meta_lines,
        )

        fp.write(content + "\n\n")

    fp.close()
    print(f"[amcli] Generated model: {output_path}")
