#!/usr/bin/env python3

import sys
import getopt
import yaml


def usage():
    print(f"Usage : {sys.argv[0]} -o <output> <input>...")


def read_yaml(path):
    with open(path, "r", encoding="utf-8") as fp:
        return yaml.safe_load(fp)


# ============================================================
# ViewSet 生成
# ============================================================
def generate_viewset(fp, model, fields):
    model_lower = model.lower()
    serializer = f"{model}Serializer"

    fp.write(f"# Generated by generate_view.py for {model}\n")
    fp.write("from django.apps import apps\n")
    fp.write("from rest_framework import viewsets\n\n")

    fp.write(f"class {model}ViewSet(viewsets.ModelViewSet):\n")
    fp.write("    queryset = None\n\n")

    fp.write("    def get_queryset(self):\n")
    fp.write(f"        Model = apps.get_model('myapp', '{model}')\n")
    fp.write("        return Model.objects.all()\n\n")

    fp.write("    def get_serializer_class(self):\n")
    fp.write(f"        from myapp.serializers.{model_lower}_serializer import {serializer}\n")
    fp.write(f"        return {serializer}\n\n")

    fp.write('    lookup_field = "id"\n\n')


# ============================================================
# main
# ============================================================
def main():
    try:
        options, args = getopt.getopt(
            sys.argv[1:], "hvo:", ["help", "version", "output="]
        )
    except getopt.GetoptError as err:
        print(str(err))
        sys.exit(1)

    output = None
    for option, optarg in options:
        if option in ("-o", "--output"):
            output = optarg

    if output:
        fp = open(output, "w", encoding="utf-8")
    else:
        fp = sys.stdout

    if not args:
        print("ERROR: no input YAML files", file=sys.stderr)
        usage()
        sys.exit(1)

    for filepath in args:
        data = read_yaml(filepath)
        model = data["name"]
        fields = data["fields"]

        generate_viewset(fp, model, fields)

    if output:
        fp.close()


if __name__ == "__main__":
    main()
