#!/usr/bin/env python3
# file: tools/generate_serializer.py

import sys
import json
import getopt
from pathlib import Path
from amcli.utils.constants import FieldType

# ★ Updated UUID（この版が反映されているかを生成ファイルで確認するため）
UUID = "d4c8e7a1-3b29-4f6c-9a8e-1f2b7c3d9e45"

HEADER = """# Generated by tools/generate_serializer.py for {model}
# UUID: """ + UUID + """
# Template: tools/generate_serializer.py
from rest_framework import serializers
from myapp.models import *
"""

def usage():
    print("Usage: generate_serializer.py -s SCHEMA_JSON -r REF_JSON -o OUTPUT_FILE")
    sys.exit(1)

def read_json(path):
    with open(path, "r", encoding="utf-8") as fp:
        return json.load(fp)

def debug(msg):
    print(f"[DEBUG] {msg}")

def build_serializer(model, fields, reverse_dependencies, reverse_detail, all_models):
    debug(f"=== Building serializer for model={model} ===")

    # 逆参照情報をデバッグ出力
    rev = reverse_dependencies.get(model, [])
    debug(f"reverse_dependencies[{model}] = {rev}")
    for other in rev:
        debug(f"reverse_dependencies_detail[{other}] = {reverse_detail.get(other)}")

    lines = []
    lines.append(HEADER.format(model=model))
    lines.append(f"class {model}Serializer(serializers.ModelSerializer):")

    fk_fields = []
    write_fk_fields = []

    # ---------------------------------------------------------
    # ForeignKey / OneToOne → read-only + write-only の両方を生成
    # ---------------------------------------------------------
    for fname, fdef in fields.items():
        ftype = fdef["type"]

        if ftype in (FieldType.FOREIGN_KEY, FieldType.ONE_TO_ONE):
            if "to" not in fdef:
                debug(f"[WARN] FK field '{fname}' (type={ftype}) has no 'to'. Skipping FK wiring.")
                continue

            debug(f"FK detected: {fname} -> {fdef['to']}")

            # read-only
            lines.append(f"    {fname} = serializers.PrimaryKeyRelatedField(read_only=True)")

            # related_model は schema["models"] から逆引きする
            related_model = None
            for mname in all_models.keys():
                if mname.lower() == fdef["to"].lower():
                    related_model = mname
                    break

            if related_model is None:
                debug(f"[WARN] Cannot resolve related model for FK field '{fname}' (to={fdef['to']}). Skipping.")
                continue

            # write-only: {fname}_id
            write_name = f"{fname}_id"
            write_fk_fields.append((write_name, fname))

            lines.append(
                f"    {write_name} = serializers.PrimaryKeyRelatedField("
                f"queryset={related_model}.objects.all(), write_only=True)"
            )

            fk_fields.append((fname, write_name))

    # ---------------------------------------------------------
    # 逆参照 OneToMany（many=True, read_only=True, required=False）
    # ---------------------------------------------------------
    debug("=== OneToMany reverse dependency generation ===")
    for other_model in rev:
        rel = reverse_detail.get(other_model)
        debug(f"Checking reverse relation: other_model={other_model}, rel={rel}")

        if rel and rel.get("type") == "OneToMany":
            field_name = f"{other_model.lower()}s"
            debug(f"→ Generating reverse field: {field_name}")
            lines.append(
                f"    {field_name} = serializers.PrimaryKeyRelatedField("
                f"many=True, read_only=True, required=False)"
            )
        else:
            debug(f"→ Skipped reverse field for {other_model}: type is not OneToMany")

    # ---------------------------------------------------------
    # ManyToMany（through）
    # ---------------------------------------------------------
    for fname, fdef in fields.items():
        if fdef["type"] == FieldType.MANY_TO_MANY:
            debug(f"M2M detected: {fname}")
            lines.append(
                f"    {fname} = serializers.PrimaryKeyRelatedField(many=True, read_only=True)"
            )

    # ---------------------------------------------------------
    # Meta.fields
    # ---------------------------------------------------------
    lines.append("")
    lines.append("    class Meta:")
    lines.append(f"        model = {model}")
    lines.append("        fields = [")

    # モデルのフィールド
    for fname in fields.keys():
        lines.append(f'            "{fname}",')

    # write-only FK フィールド
    for write_name, _orig in write_fk_fields:
        lines.append(f'            "{write_name}",')

    # 逆参照フィールド
    for other_model in rev:
        rel = reverse_detail.get(other_model)
        if rel and rel.get("type") == "OneToMany":
            field_name = f"{other_model.lower()}s"
            lines.append(f'            "{field_name}",')

    # ManyToMany
    for fname, fdef in fields.items():
        if fdef["type"] == FieldType.MANY_TO_MANY:
            lines.append(f'            "{fname}",')

    lines.append("        ]")
    lines.append("")

    # ---------------------------------------------------------
    # create() を自動生成
    # ---------------------------------------------------------
    lines.append("    def create(self, validated_data):")

    for fname, write_name in fk_fields:
        lines.append(f"        {fname} = validated_data.pop('{write_name}', None)")
        lines.append(f"        if {fname} is not None:")
        lines.append(f"            validated_data['{fname}'] = {fname}")

    lines.append(f"        return {model}.objects.create(**validated_data)")
    lines.append("")
    lines.append("# End of file (tools/generate_serializer.py)")
    lines.append("")

    return "\n".join(lines)

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "s:r:o:", ["schema=", "ref=", "output="])
    except getopt.GetoptError:
        usage()

    schema_json = None
    ref_json = None
    output_file = None

    for opt, val in opts:
        if opt in ("-s", "--schema"):
            schema_json = val
        elif opt in ("-r", "--ref"):
            ref_json = val
        elif opt in ("-o", "--output"):
            output_file = val

    if not schema_json or not ref_json or not output_file:
        usage()

    schema = read_json(schema_json)
    reverse_dependencies = schema["reverse_dependencies"]

    # ★ reverse_dependencies_detail_mod を優先して参照する
    reverse_detail_mod = schema.get("reverse_dependencies_detail_mod", {})
    debug(f"[MOD] reverse_dependencies_detail_mod = {reverse_detail_mod}")

    reverse_detail = reverse_detail_mod or schema.get("reverse_dependencies_detail", {})
    debug(f"[MOD] reverse_dependencies_detail = {reverse_detail}")

    data = read_json(ref_json)
    model = data["name"]
    fields = data["fields"]

    debug(f"Loaded schema for model={model}")
    debug(f"reverse_dependencies keys={list(reverse_dependencies.keys())}")

    content = build_serializer(
        model=model,
        fields=fields,
        reverse_dependencies=reverse_dependencies,
        reverse_detail=reverse_detail,
        all_models=schema["models"],
    )

    out_path = Path(output_file)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as fp:
        fp.write(content)

    print(f"[OK] Generated serializer: {output_file}")

if __name__ == "__main__":
    main()
