#!/usr/bin/env python3
# file: tools/generate_serializer.py

import sys
import json
import getopt
from pathlib import Path
from amcli.utils.constants import FieldType

import os

from amcli.utils.debug import debug



UUID = "d4c8e7a1-3b29-4f6c-9a8e-1f2b7c3d9e45"

HEADER = """# Generated by tools/generate_serializer.py for {model}
# UUID: """ + UUID + """
# Template: tools/generate_serializer.py
from rest_framework import serializers
from myapp.models import *
"""

def usage():
    print("Usage: generate_serializer.py -s SCHEMA_JSON -r REF_JSON -o OUTPUT_FILE")
    sys.exit(1)

def read_json(path):
    with open(path, "r", encoding="utf-8") as fp:
        return json.load(fp)

def build_root_serializer(model, nested, schema_models):
    lines = []
    lines.append(HEADER.format(model=model))

    child_models = []

    for item in nested:
        kind = item["kind"]
        if kind == "one_to_many":
            child_model = item["model"]
            if child_model not in child_models:
                child_models.append(child_model)
        elif kind == "many_to_many":
            root_fields = schema_models[model]["fields"]
            field_def = root_fields.get(item["name"])
            if field_def and "to" in field_def:
                m2m_model = field_def["to"]
                if m2m_model not in child_models:
                    child_models.append(m2m_model)

    for child in child_models:
        lines.append("")
        lines.append(f"class {child}Serializer(serializers.ModelSerializer):")
        lines.append("    class Meta:")
        lines.append(f"        model = " + child)
        lines.append('        fields = "__all__"')
        lines.append("        depth = 3")

    lines.append("")
    lines.append(f"class {model}Serializer(serializers.ModelSerializer):")

    for item in nested:
        name = item["name"]
        kind = item["kind"]
        if kind == "one_to_many":
            child_model = item["model"]
            lines.append(
                f"    {name} = {child_model}Serializer(many=True, read_only=True)"
            )
        elif kind == "many_to_many":
            root_fields = schema_models[model]["fields"]
            field_def = root_fields.get(name)
            if field_def and "to" in field_def:
                m2m_model = field_def["to"]
                lines.append(
                    f"    {name} = {m2m_model}Serializer(many=True, read_only=True)"
                )

    lines.append("")
    lines.append("    class Meta:")
    lines.append(f"        model = {model}")
    lines.append('        fields = "__all__"')
    lines.append("        depth = 3")
    lines.append("")
    lines.append("# End of file (tools/generate_serializer.py)")
    lines.append("")
    return "\n".join(lines)

def build_default_serializer(model, fields, reverse_dependencies, reverse_detail, all_models):
    debug(f"=== Building default serializer for model={model} ===")

    rev = reverse_dependencies.get(model, [])
    lines = []
    lines.append(HEADER.format(model=model))
    lines.append(f"class {model}Serializer(serializers.ModelSerializer):")

    fk_fields = []
    write_fk_fields = []

    for fname, fdef in fields.items():
        ftype = fdef["type"]

        if ftype in (FieldType.FOREIGN_KEY, FieldType.ONE_TO_ONE):
            if "to" not in fdef:
                continue

            lines.append(f"    {fname} = serializers.PrimaryKeyRelatedField(read_only=True)")

            related_model = None
            for mname in all_models.keys():
                if mname.lower() == fdef["to"].lower():
                    related_model = mname
                    break

            write_name = f"{fname}_id"
            write_fk_fields.append((write_name, fname))

            lines.append(
                f"    {write_name} = serializers.PrimaryKeyRelatedField("
                f"queryset={related_model}.objects.all(), write_only=True)"
            )

            fk_fields.append((fname, write_name))

    for other_model in rev:
        rel = reverse_detail.get(other_model)
        if rel and rel.get("type") == "OneToMany":
            field_name = f"{other_model.lower()}s"
            lines.append(
                f"    {field_name} = serializers.PrimaryKeyRelatedField("
                f"many=True, read_only=True, required=False)"
            )

    for fname, fdef in fields.items():
        if fdef["type"] == FieldType.MANY_TO_MANY:
            lines.append(
                f"    {fname} = serializers.PrimaryKeyRelatedField(many=True, read_only=True)"
            )

    lines.append("")
    lines.append("    class Meta:")
    lines.append(f"        model = {model}")
    lines.append("        fields = [")

    for fname in fields.keys():
        lines.append(f'            "{fname}",')

    for write_name, _orig in write_fk_fields:
        lines.append(f'            "{write_name}",')

    for other_model in rev:
        rel = reverse_detail.get(other_model)
        if rel and rel.get("type") == "OneToMany":
            field_name = f"{other_model.lower()}s"
            lines.append(f'            "{field_name}",')

    for fname, fdef in fields.items():
        if fdef["type"] == FieldType.MANY_TO_MANY:
            lines.append(f'            "{fname}",')

    lines.append("        ]")
    lines.append("")
    lines.append("    def create(self, validated_data):")
    for fname, write_name in fk_fields:
        lines.append(f"        {fname} = validated_data.pop('{write_name}', None)")
        lines.append(f"        if {fname} is not None:")
        lines.append(f"            validated_data['{fname}'] = {fname}")
    lines.append(f"        return {model}.objects.create(**validated_data)")
    lines.append("")
    lines.append("# End of file (tools/generate_serializer.py)")
    lines.append("")
    return "\n".join(lines)

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "s:r:o:", ["schema=", "ref=", "output="])
    except getopt.GetoptError:
        usage()

    schema_json = None
    ref_json = None
    output_file = None

    for opt, val in opts:
        if opt in ("-s", "--schema"):
            schema_json = val
        elif opt in ("-r", "--ref"):
            ref_json = val
        elif opt in ("-o", "--output"):
            output_file = val

    if not schema_json or not ref_json or not output_file:
        usage()

    schema = read_json(schema_json)
    reverse_dependencies = schema["reverse_dependencies"]
    reverse_detail_mod = schema.get("reverse_dependencies_detail_mod", {})
    reverse_detail = reverse_detail_mod or schema.get("reverse_dependencies_detail", {})
    nested = schema.get("nested", {})
    models_def = schema["models"]

    composition_root = schema.get("composition_root")
    root_models = [composition_root] if composition_root else []
    root_models = [m.lower() for m in root_models]

    data = read_json(ref_json)
    model = data["name"]
    model_lower = model.lower()
    fields = data["fields"]

    debug(f"[ROOT] composition_root = {composition_root}")
    debug(f"[ROOT] root_models(normalized) = {root_models}")

    if model_lower in root_models:
        nested_info = nested.get(model, [])
        content = build_root_serializer(model, nested_info, models_def)
    else:
        content = build_default_serializer(
            model=model,
            fields=fields,
            reverse_dependencies=reverse_dependencies,
            reverse_detail=reverse_detail,
            all_models=models_def,
        )

    out_path = Path(output_file)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as fp:
        fp.write(content)

    debug(f"[OK] Generated serializer: {output_file}")

if __name__ == "__main__":
    main()
